import { Track } from '@/types'

export const TRACKS: Track[] = [
  {
    id: 'piano-saudade',
    name: 'Saudade do Coração',
    artist: 'MotherRoll Studio',
    category: 'piano',
    categoryLabel: '🎹 Piano Suave',
    file: '/audio/piano-saudade.mp3',
    duration: 180,
    previewStart: 0,
  },
  {
    id: 'piano-ternura',
    name: 'Ternura',
    artist: 'MotherRoll Studio',
    category: 'piano',
    categoryLabel: '🎹 Piano Suave',
    file: '/audio/piano-ternura.mp3',
    duration: 165,
    previewStart: 10,
  },
  {
    id: 'romantica-sempre',
    name: 'Para Sempre',
    artist: 'MotherRoll Studio',
    category: 'romantica',
    categoryLabel: '🌹 Romântica',
    file: '/audio/romantica-sempre.mp3',
    duration: 190,
    previewStart: 0,
  },
  {
    id: 'romantica-amor',
    name: 'Amor Eterno',
    artist: 'MotherRoll Studio',
    category: 'romantica',
    categoryLabel: '🌹 Romântica',
    file: '/audio/romantica-amor.mp3',
    duration: 175,
    previewStart: 5,
  },
  {
    id: 'instrumental-leveza',
    name: 'Leveza',
    artist: 'MotherRoll Studio',
    category: 'instrumental',
    categoryLabel: '🎻 Instrumental',
    file: '/audio/instrumental-leveza.mp3',
    duration: 200,
    previewStart: 0,
  },
  {
    id: 'instrumental-tempo',
    name: 'O Tempo e Nós',
    artist: 'MotherRoll Studio',
    category: 'instrumental',
    categoryLabel: '🎻 Instrumental',
    file: '/audio/instrumental-tempo.mp3',
    duration: 185,
    previewStart: 15,
  },
  {
    id: 'inspiradora-forca',
    name: 'Força',
    artist: 'MotherRoll Studio',
    category: 'inspiradora',
    categoryLabel: '✨ Inspiradora',
    file: '/audio/inspiradora-forca.mp3',
    duration: 170,
    previewStart: 0,
  },
  {
    id: 'inspiradora-gratidao',
    name: 'Gratidão',
    artist: 'MotherRoll Studio',
    category: 'inspiradora',
    categoryLabel: '✨ Inspiradora',
    file: '/audio/inspiradora-gratidao.mp3',
    duration: 195,
    previewStart: 10,
  },
  {
    id: 'especial-familia',
    name: 'Família',
    artist: 'MotherRoll Studio',
    category: 'especial',
    categoryLabel: '💛 Especial',
    file: '/audio/especial-familia.mp3',
    duration: 210,
    previewStart: 0,
  },
  {
    id: 'especial-memoria',
    name: 'Memória',
    artist: 'MotherRoll Studio',
    category: 'especial',
    categoryLabel: '💛 Especial',
    file: '/audio/especial-memoria.mp3',
    duration: 180,
    previewStart: 20,
  },
]

export const CATEGORIES = [
  { id: 'piano',        label: '🎹 Piano Suave' },
  { id: 'romantica',    label: '🌹 Romântica' },
  { id: 'instrumental', label: '🎻 Instrumental' },
  { id: 'inspiradora',  label: '✨ Inspiradora' },
  { id: 'especial',     label: '💛 Especial' },
]

export function getTrackById(id: string): Track | undefined {
  return TRACKS.find(t => t.id === id)
}
